# Generated by Django 3.2.6 on 2021-09-01 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thebinaries', '0002_auto_20210901_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('photo', models.ImageField(blank=True, upload_to='members/', verbose_name='Photo')),
                ('description', models.TextField(max_length='2000', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='service',
            name='illustration',
            field=models.CharField(choices=[('/static/images/illustrations/web_design.png', 'Web Design'), ('/static/images/illustrations/web_dev.png', 'Web Development'), ('/static/images/illustrations/ui_ux.png', 'UI/UX'), ('/static/images/illustrations/app_dev.png', 'App Development'), ('/static/images/illustrations/digital_m.png', 'Digital Marketing'), ('/static/images/illustrations/seo.png', 'SEO')], max_length=1028, verbose_name='Service Illustration'),
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Number', (('PH fas fa-phone-alt', 'Phone'), ('WA fab fa-whatsapp', 'Whatsapp'), ('VB fab fa-viber', 'Viber'))), ('Mail', (('EM fas fa-envelope', 'Email'), ('EM fab fa-google', 'Gmail'))), ('link', (('FB fab fa-facebook', 'Facebook'), ('IG fab fa-instagram', 'Instagram'), ('LI fab fa-linkedin', 'LinkedIn'), ('TW fab fa-twitter', 'Twitter'), ('YT fab fa-youtube', 'Youtube'), ('TG fab fa-telegram-plane', 'Telegram'), ('RD fab fa-reddit', 'Reddit'), ('SK fab fa-skype', 'Skype'), ('TR fab fa-tumblr-square', 'Tumblr'), ('TT fab fa-tiktok', 'Tiktok'), ('OT fas fa-link', 'Others')))], max_length=100, verbose_name='platform *')),
                ('link_name', models.CharField(help_text='For example : Facebook page , Whatsapp number etc.', max_length=255, verbose_name='Link Name *')),
                ('link', models.CharField(help_text='This can contain Number, Email address and Link. Choose according to platform.', max_length=2083, verbose_name='Link | Number | Email *')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thebinaries.member')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Medias',
            },
        ),
    ]
