# Generated by Django 3.2.6 on 2021-09-01 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thebinaries', '0006_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(help_text='Can add multiple phone numbers by seperating with space .', max_length=256, verbose_name='Phone Numbers')),
                ('about', models.TextField(blank=True, max_length=1000, verbose_name='About')),
                ('tagline', models.CharField(blank=True, max_length=256, verbose_name='Tagline')),
                ('tagline_description', models.TextField(blank=True, max_length=1000, verbose_name='Talgine Bio')),
                ('locations', models.TextField(blank=True, max_length=2000, verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Other Information',
                'verbose_name_plural': 'Other Informations',
            },
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='thebinaries.member'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='medias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thebinaries.otherinformation'),
        ),
    ]
