# Generated by Django 3.2.6 on 2021-09-03 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thebinaries', '0007_auto_20210901_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='medias',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='thebinaries.otherinformation'),
        ),
    ]
