# Generated by Django 3.2.5 on 2021-07-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='date_added',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
